### PR TITLE
Fixed default child item(circle image) in design

### PR DESCRIPTION
**Pull request by Y-E-P**
Before 
device-2015-11-05-142520
After device-2015-11-05-142322

### CODE REVIEW

**Comment by Rainer-Lang** [comment]
@saulmm Could you merge this please?

**Comment by Y-E-P** [comment]
Yes,tommorow,ok??
19 дек. 2015 г. 19:53 пользователь "Rainer-Lang" <notifications@github.com>
написал:

**Comment by saulmm** [comment]
Looks good! Just one thing, Could you respect the current indentation of the file?. Will merge by then ;). Thanks for your contribution!

**Comment by saulmm** [comment]
Could you open a new PR after the last master point? Thanks!

**Pull request closed without merging**
